// <auto-generated />
using LagusImoveisWebII.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LagusImoveisWebII.Migrations
{
    [DbContext(typeof(LagusImoveisWebIIContext))]
    partial class LagusImoveisWebIIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("bairro");

                    b.Property<int>("Cep")
                        .HasColumnType("integer")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cidade");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("integer")
                        .HasColumnName("idPropriedade");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("rua");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId")
                        .IsUnique();

                    b.ToTable("endereco", (string)null);
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.Imagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Imagens")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("imagem");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("integer")
                        .HasColumnName("idPropriedade");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("imagem", (string)null);
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.Propriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descricao");

                    b.Property<int>("TipoImovelID")
                        .HasColumnType("integer")
                        .HasColumnName("idTipoImovel");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("idUsuario");

                    b.HasKey("Id");

                    b.HasIndex("TipoImovelID");

                    b.HasIndex("UsuarioId");

                    b.ToTable("propriedade", (string)null);
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.PropriedadeTipoSituacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("integer")
                        .HasColumnName("idpropriedade");

                    b.Property<int>("TipoSituacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("idTipoSituacao");

                    b.Property<decimal>("Valor")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.HasIndex("TipoSituacaoId");

                    b.ToTable("propriedade_tipo_situacao", (string)null);
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.TipoImovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("tipoImovel", (string)null);
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.TipoSituacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("tipoSituacao", (string)null);
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("senha");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("sobrenome");

                    b.Property<int>("Telefone")
                        .HasColumnType("integer")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.Endereco", b =>
                {
                    b.HasOne("LagusImoveisWebII.Models.Entites.Propriedade", "Propriedade")
                        .WithOne()
                        .HasForeignKey("LagusImoveisWebII.Models.Entites.Endereco", "PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.Imagem", b =>
                {
                    b.HasOne("LagusImoveisWebII.Models.Entites.Propriedade", "Propriedade")
                        .WithMany("Imagem")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.Propriedade", b =>
                {
                    b.HasOne("LagusImoveisWebII.Models.Entites.TipoImovel", "TipoImovel")
                        .WithMany("Propriedade")
                        .HasForeignKey("TipoImovelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LagusImoveisWebII.Models.Entites.Usuario", "Usuario")
                        .WithMany("Propriedade")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoImovel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.PropriedadeTipoSituacao", b =>
                {
                    b.HasOne("LagusImoveisWebII.Models.Entites.Propriedade", "Propriedade")
                        .WithMany("PropriedadeTipoSituacao")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LagusImoveisWebII.Models.Entites.TipoSituacao", "TipoSituacao")
                        .WithMany("PropriedadeTipoSituacao")
                        .HasForeignKey("TipoSituacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");

                    b.Navigation("TipoSituacao");
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.Propriedade", b =>
                {
                    b.Navigation("Imagem");

                    b.Navigation("PropriedadeTipoSituacao");
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.TipoImovel", b =>
                {
                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.TipoSituacao", b =>
                {
                    b.Navigation("PropriedadeTipoSituacao");
                });

            modelBuilder.Entity("LagusImoveisWebII.Models.Entites.Usuario", b =>
                {
                    b.Navigation("Propriedade");
                });
#pragma warning restore 612, 618
        }
    }
}
